---
- name: Setup Plex Movie Poster
  hosts: RemoteHost
  remote_user: gschroeder
  become: yes

  roles:
    - role: setup
      tags: ['setup']

    - role: prereq
      tags: ['prereq']

    - role: nginx
      tags: ['nginx']
    
    - role: php
      tags: ['php']

    - role: git
      tags: ['git']